"""A8 - the fitted response surface: health state -> 21 sensor readings.

THIS IS THE FITTED HALF OF THE REPLICATION, and it is deliberately kept in its
own module so the boundary with damage.py (which is exact, from published
equations) stays visible and auditable.

WHY IT HAS TO BE FITTED
    The paper's Figure 4 shows a response surface mapping efficiency and flow
    loss to a sensor value, generated by the C-MAPSS thermodynamic model. That
    model was never publicly released, so the surfaces cannot be reproduced from
    first principles. They are instead recovered from the released data.

FIT ON TRAIN UNITS ONLY
    Every coefficient here is estimated from train_FDxxx.txt. The test split is
    never touched, so the TSTR gate (A17) - train a model on our synthetic data,
    evaluate it on NASA's real test set - remains an honest held-out comparison.

FUNCTIONAL FORM, CHOSEN FROM THE DATA NOT ASSUMED
    Regressing each informative FD001 sensor on normalised life shows quadratic
    consistently beating linear (e.g. T50 R^2 0.506 -> 0.606, Ps30 0.529 ->
    0.633) while cubic adds almost nothing (0.617, 0.645). So the mean trend is
    quadratic in health. Measured, recorded, and re-measured per subset rather
    than hardcoded.

NOISE DECOMPOSITION FEEDS A9
    In FD001 the within-unit standard deviation is 0.79-0.99 of the total for
    every sensor, i.e. C-MAPSS is noise-dominated and the degradation trend is a
    minority of the variance. We split the residual into a between-unit
    component (one offset per unit - manufacturing variation and the process
    noise that the paper filters through the engine model) and a within-unit
    component (per-cycle measurement noise). A9 reproduces both, in that order,
    which is the order the paper specifies.
"""
from __future__ import annotations

import json
import os
from dataclasses import dataclass, field

import numpy as np
import pandas as pd

from . import config as C
from . import damage as D
from . import parser as P
from . import noise as N


# ---------------------------------------------------------------------------
# Assigning a health trajectory to a REAL unit.
#
# The real data does not expose efficiency, flow or health - only sensors and
# the fact that each train unit ends at failure. To fit sensors against health
# we must first say what health each real row was at.
#
# We do that with the damage model itself rather than an ad-hoc proxy: given a
# unit's observed length L, solve for the rate `a` that makes the calibrated
# model fail exactly at cycle L (holding b at the centre of its published
# range). That yields a health curve consistent with the degradation law, and it
# keeps the surrogate's input in the same units the generator will later
# produce. A raw life-fraction proxy would be simpler but would break that
# correspondence, because health is not linear in life fraction.
# ---------------------------------------------------------------------------

def health_for_length(length: int, gain: float, b: float | None = None,
                      tol: float = 1e-4, iters: int = 80) -> np.ndarray:
    """Health trajectory for a real unit observed to fail at `length` cycles."""
    if b is None:
        b = 0.5 * (C.B_RANGE[0] + C.B_RANGE[1])

    def sim_len(a: float) -> int:
        p = D.UnitDamageParams(unit=0, e0=1.0, f0=1.0, a_e=a, b_e=b, a_f=a, b_f=b, k=1)
        return D.simulate_unit(p, max_cycles=max(4 * length, 1000), gain=gain)["length"]

    # Length decreases monotonically in a, so bisect geometrically.
    lo, hi = 1e-8, 1.0
    for _ in range(iters):
        mid = np.sqrt(lo * hi)
        if sim_len(mid) > length:
            lo = mid
        else:
            hi = mid
        if hi / lo < 1 + tol:
            break
    a = float(np.sqrt(lo * hi))

    p = D.UnitDamageParams(unit=0, e0=1.0, f0=1.0, a_e=a, b_e=b, a_f=a, b_f=b, k=1)
    run = D.simulate_unit(p, max_cycles=max(4 * length, 1000), gain=gain)
    h = run["health"]
    # Resample onto exactly `length` cycles: the inversion lands within a cycle
    # or two, and forcing an exact match keeps the join with the real rows clean.
    if h.size != length:
        h = np.interp(np.linspace(0, 1, length), np.linspace(0, 1, h.size), h)
    return h


def assign_health(train: pd.DataFrame, gain, unit_mode: dict | None = None) -> np.ndarray:
    """Health for every row of a train split, via per-unit inversion.

    Units of equal length share a curve, so the inversion is cached - FD004 has
    249 units but far fewer distinct lengths.
    """
    lengths = train.groupby("unit")["cycle"].max()

    def gain_for(unit: int) -> float:
        if isinstance(gain, dict):
            return gain[unit_mode[int(unit)] if unit_mode else 0]
        return gain

    # Cache on (length, gain): units of different fault modes use different
    # gains, so length alone no longer identifies a curve.
    cache: dict[tuple, np.ndarray] = {}
    for unit in lengths.index:
        key = (int(lengths.loc[unit]), gain_for(unit))
        if key not in cache:
            cache[key] = health_for_length(key[0], key[1])

    out = np.empty(len(train), dtype=float)
    pos = 0
    for unit, grp in train.groupby("unit", sort=True):
        n = len(grp)
        curve = cache[(int(lengths.loc[unit]), gain_for(unit))]
        # grp is ordered by cycle; index the curve by cycle-1.
        out[pos:pos + n] = curve[grp["cycle"].to_numpy() - 1]
        pos += n
    return out


# ---------------------------------------------------------------------------
# The response surface itself.
# ---------------------------------------------------------------------------

def gkey(mode: int, regime: int) -> str:
    """Key for one (fault mode, operating regime) group."""
    return f"m{int(mode)}r{int(regime)}"


@dataclass
class ResponseSurface:
    """Per-(regime, sensor) quadratic in health, plus a two-level noise model."""
    subset: str
    degree: int
    sensors: list[str]
    regime_centres: np.ndarray
    # coef[regime][sensor] -> polynomial coefficients, highest power first
    coef: dict = field(default_factory=dict)
    between_unit_sd: dict = field(default_factory=dict)   # [regime][sensor]
    within_unit_sd: dict = field(default_factory=dict)    # [regime][sensor]
    noise_params: dict = field(default_factory=dict)      # [regime][sensor] -> phi/var/kurtosis
    constant_values: dict = field(default_factory=dict)   # [regime][sensor] for flat channels
    constant_sensors: list = field(default_factory=list)
    # [regime] -> {"mean": [3], "sd": [3], "weight": float} for the operating
    # settings columns, so generated rows carry settings with the same spread
    # and the same regime occupancy as the real data.
    regime_settings: dict = field(default_factory=dict)
    # Fault-mode structure. Single-fault subsets have one mode and these are
    # trivial; two-fault subsets carry a per-mode gain and unit share, because
    # the two modes are genuinely different lifetime populations (FD003: mean
    # 202 vs 305 cycles, silhouette 0.69).
    n_modes: int = 1
    mode_weights: list = field(default_factory=lambda: [1.0])
    gains: dict = field(default_factory=dict)
    mode_diag: dict = field(default_factory=dict)
    # [sensor] -> quantisation step observed in the released data. Several
    # channels are discretised (htBleed is integer-valued with 13 distinct
    # levels; P15 takes just 2 values) and emitting them as continuous floats
    # is visible to a distribution test.
    quantum: dict = field(default_factory=dict)
    # [group] -> {"cols": [...], "corr": [[...]]} for the WITHIN-UNIT RESIDUALS.
    # Real sensors share the engine's process noise, so their noise is
    # correlated across channels (mean |corr| 0.118, max 0.931 in FD001).
    # Generating each channel independently leaves that at 0.007 and makes a
    # single row trivially recognisable even when every marginal matches.
    resid_corr: dict = field(default_factory=dict)
    # [sensor] -> {"values", "cumprob"} for channels taking only a handful of
    # distinct levels. These are discretised versions of an underlying
    # continuous quantity, and the discretisation thresholds are not recoverable
    # from the quantum alone - on a 2-level channel like P15 a sub-0.001 error
    # in the continuous mean becomes a visible shift in level proportions.
    # Stored from TRAIN only, like every other fitted quantity here.
    low_card: dict = field(default_factory=dict)

    # -- prediction ---------------------------------------------------------
    def mean_response(self, health: np.ndarray, regime: int) -> dict[str, np.ndarray]:
        """Noise-free sensor values for a health trajectory in one regime."""
        health = np.asarray(health, dtype=float)
        out = {}
        for s in C.SENSOR_COLS:
            if s in self.constant_sensors:
                out[s] = np.full(health.shape, self.constant_values[regime][s])
            else:
                out[s] = np.polyval(self.coef[regime][s], health)
        return out

    # -- persistence --------------------------------------------------------
    def to_dict(self) -> dict:
        return {
            "subset": self.subset, "degree": self.degree, "sensors": self.sensors,
            "regime_centres": np.asarray(self.regime_centres).tolist(),
            "coef": {k_: {s: np.asarray(c).tolist() for s, c in d.items()}
                     for k_, d in self.coef.items()},
            "between_unit_sd": self.between_unit_sd,
            "within_unit_sd": self.within_unit_sd,
            "noise_params": self.noise_params,
            "constant_values": self.constant_values,
            "constant_sensors": self.constant_sensors,
            "regime_settings": {str(r): d for r, d in self.regime_settings.items()},
            "quantum": self.quantum,
            "resid_corr": self.resid_corr,
            "n_modes": self.n_modes,
            "mode_weights": self.mode_weights,
            "gains": {str(k_): v for k_, v in self.gains.items()},
            "mode_diag": self.mode_diag,
            "low_card": self.low_card,
            "provenance": {
                "status": "FITTED",
                "fitted_on": "train split only; test never touched",
                "reason": "C-MAPSS thermodynamic model unreleased, so the response "
                          "surfaces of Fig.4 cannot be reproduced from first principles",
            },
        }

    @classmethod
    def from_dict(cls, d: dict) -> "ResponseSurface":
        rs = cls(subset=d["subset"], degree=d["degree"], sensors=d["sensors"],
                 regime_centres=np.asarray(d["regime_centres"], dtype=float))
        rs.coef = {k_: {s: np.asarray(c, float) for s, c in v.items()}
                   for k_, v in d["coef"].items()}
        rs.between_unit_sd = d["between_unit_sd"]
        rs.within_unit_sd = d["within_unit_sd"]
        rs.noise_params = d.get("noise_params", {})
        rs.constant_values = d["constant_values"]
        rs.constant_sensors = d["constant_sensors"]
        rs.regime_settings = {int(r): v for r, v in d.get("regime_settings", {}).items()}
        rs.quantum = d.get("quantum", {})
        rs.resid_corr = d.get("resid_corr", {})
        rs.n_modes = d.get("n_modes", 1)
        rs.mode_weights = d.get("mode_weights", [1.0])
        rs.gains = {int(k_): v for k_, v in d.get("gains", {}).items()}
        rs.mode_diag = d.get("mode_diag", {})
        rs.low_card = d.get("low_card", {})
        return rs

    def save(self, path: str) -> None:
        with open(path, "w") as fh:
            json.dump(self.to_dict(), fh, indent=2)

    @classmethod
    def load(cls, path: str) -> "ResponseSurface":
        with open(path) as fh:
            return cls.from_dict(json.load(fh))


def _raw_lag1_acf(sub: pd.DataFrame, col: str) -> float:
    """Mean within-unit lag-1 autocorrelation of a channel, as generated data
    will be measured by the fidelity gate. Units where the channel is flat have
    no defined autocorrelation and are skipped rather than counted as zero."""
    acc = []
    for _, g in sub.groupby("unit"):
        x = g[col].to_numpy(float)
        if x.size > 5 and x.std() > 1e-12:
            v = np.corrcoef(x[:-1], x[1:])[0, 1]
            if np.isfinite(v):
                acc.append(float(v))
    return float(np.mean(acc)) if acc else 0.0


def _solve_generation_phi(base: np.ndarray, var_n: float, target_acf: float,
                          var_extra: float = 0.0) -> float:
    """AR(1) coefficient for the smooth component so the TOTAL signal hits
    `target_acf` at lag 1.

    The generated channel is base + smooth + white, all independent, so

        acf = [var_base.rho_base + var_smooth.phi] / (var_base + var_smooth + var_white)

    which inverts directly. `var_extra` is the white variance: it adds to the
    denominator but contributes nothing to lag-1 covariance, which is exactly
    why a white-dominated channel ends up with a low total autocorrelation.
    """
    if var_n <= 0 or base.size < 3:
        return 0.0
    b = base - base.mean()
    var_s = float(b.var())
    total = var_s + var_n + var_extra
    if var_s <= 0:
        return float(np.clip(target_acf * total / var_n, 0.0, 0.95))
    rho_s = float(np.dot(b[:-1], b[1:]) / np.dot(b, b))
    phi = (target_acf * total - var_s * rho_s) / var_n
    return float(np.clip(phi, 0.0, 0.95))


def assign_regimes(df: pd.DataFrame, centres: np.ndarray) -> np.ndarray:
    """Nearest-centre regime label for each row."""
    X = df[C.SETTING_COLS].to_numpy(float)
    d = ((X[:, None, :] - centres[None, :, :]) ** 2).sum(-1)
    return d.argmin(1)


def fit(subset: str, gain, degree: int = 2,
        data_dir: str | None = None, unit_mode: dict | None = None,
        mode_diag: dict | None = None) -> ResponseSurface:
    """Fit the response surface on the TRAIN split only, per (fault mode, regime).

    Fitting per mode matters as much as fitting per regime on the two-fault
    subsets: a single surface averages two distinct sensor responses into one,
    and the generator can then reproduce neither.
    """
    train = P.load_split(subset, "train", data_dir)
    meta = C.SUBSETS[subset]

    from .characterize import recover_operating_regimes
    _, centres, _ = recover_operating_regimes(train, meta["n_conditions"])
    centres = np.asarray(centres, dtype=float)

    regimes = assign_regimes(train, centres)
    if unit_mode is None:
        from . import faultmode as FM
        cols_tmp = [c for c in C.SENSOR_COLS if c not in P.constant_sensors(train)]
        unit_mode, mode_diag = FM.infer_modes(
            train, subset, cols_tmp, regimes if centres.shape[0] > 1 else None)
    if not isinstance(gain, dict):
        gain = {0: gain}

    health = assign_health(train, gain, unit_mode)
    row_mode = train["unit"].map(unit_mode).to_numpy()

    # Quantisation step per channel, measured as the smallest gap between
    # distinct observed values. Derived from the data rather than assumed, so a
    # subset that discretises different channels is handled automatically.
    quantum = {}
    for s_ in C.SENSOR_COLS:
        u = np.unique(train[s_].to_numpy(float))
        gaps = np.diff(u)
        gaps = gaps[gaps > 1e-12]
        quantum[s_] = float(gaps.min()) if gaps.size else 0.0
    const = P.constant_sensors(train)
    informative = [c for c in C.SENSOR_COLS if c not in const]

    rs = ResponseSurface(subset=subset, degree=degree, sensors=informative,
                         regime_centres=centres, constant_sensors=const)
    rs.quantum = quantum
    n_modes = (mode_diag or {}).get("n_modes", 1)
    rs.n_modes = n_modes
    rs.gains = dict(gain)
    rs.mode_diag = mode_diag or {}
    rs.mode_weights = [
        float(sum(1 for v in unit_mode.values() if v == m) / len(unit_mode))
        for m in range(n_modes)]

    # Empirical level distribution for low-cardinality channels, PER REGIME.
    #
    # Per regime, not globally: in the six-condition subsets these channels are
    # largely functions of the operating point, and their levels do not overlap
    # between regimes. In FD002 farB is 0.02 in regimes 0/2/4 and 0.03 in 1/3,
    # and P15 sits near 5.71 in regime 0 but 21.60 in regime 3. Mapping such a
    # channel globally by rank hands a regime-0 row a regime-3 value, which
    # preserves the global marginal - so a marginal test still passes - while
    # destroying the channel's regime structure and any trend inside it.
    LOW_CARD_MAX = 20
    for r in range(centres.shape[0]):
        sub_r = train.loc[regimes == r]
        for s_ in C.SENSOR_COLS:
            if s_ in const or sub_r.empty:
                continue
            v = sub_r[s_].to_numpy(float)
            lv, cnt = np.unique(v, return_counts=True)
            if lv.size <= LOW_CARD_MAX:
                rs.low_card.setdefault(s_, {})[str(r)] = {
                    "values": lv.tolist(),
                    "cumprob": np.cumsum(cnt / cnt.sum()).tolist()}

    for r in range(centres.shape[0]):
        m_reg = regimes == r
        X = train.loc[m_reg, C.SETTING_COLS].to_numpy(float)
        rs.regime_settings[r] = {
            "mean": X.mean(0).tolist(),
            "sd": X.std(0, ddof=0).tolist(),
            "weight": float(m_reg.sum() / len(train)),
        }

    _resid_store: dict = {}
    for mode in range(n_modes):
      for r in range(centres.shape[0]):
        m = (regimes == r) & (row_mode == mode)
        if not m.any():
            continue
        sub = train.loc[m]
        key = gkey(mode, r)
        h = health[m]
        rs.coef[key], rs.between_unit_sd[key] = {}, {}
        rs.within_unit_sd[key], rs.constant_values[key] = {}, {}
        rs.noise_params[key] = {}

        for s in C.SENSOR_COLS:
            v = sub[s].to_numpy(float)
            if s in const:
                rs.constant_values[key][s] = float(v[0] if v.size else 0.0)
                continue

            c = np.polyfit(h, v, degree)
            rs.coef[key][s] = c
            resid = v - np.polyval(c, h)

            # Split residual: per-unit mean is between-unit variation (initial
            # wear + process noise filtered through the engine); the rest is
            # per-cycle measurement noise. A9 reproduces both in this order.
            per_unit = pd.Series(resid).groupby(sub["unit"].to_numpy()).mean()
            rs.between_unit_sd[key][s] = float(per_unit.std(ddof=0))
            within = resid - sub["unit"].map(per_unit).to_numpy()
            rs.within_unit_sd[key][s] = float(within.std(ddof=0))

            # AR(1) + mixture parameters, measured per sensor (A9). These are
            # what let the generated channels reproduce the real data's
            # autocorrelation and heavy tails rather than looking like white
            # Gaussian noise.
            meas = N.measure(resid, sub["unit"].to_numpy())

            # The phi measured on residuals is NOT the phi to generate with.
            # The generated series is base(health) + offset + noise, and the
            # base curve is smooth, so it contributes autocorrelation of its
            # own. Generating with the residual phi double-counts that and
            # leaves channels more autocorrelated than the real data (observed:
            # Nc 0.864 generated vs 0.616 real).
            #
            # Since base and noise are independent, lag-1 autocorrelation of
            # their sum is exact:
            #     acf = [var_s.rho_s + var_n.phi] / (var_s + var_n)
            # so the phi reproducing an observed total acf is
            #     phi = [acf.(var_s + var_n) - var_s.rho_s] / var_n
            # Solved here against the real channel's own raw ACF.
            meas["phi_residual"] = meas["phi"]
            meas["target_acf"] = _raw_lag1_acf(sub, s)
            # The smooth component's coefficient is set by its TIMESCALE, which
            # is what the window-variance ratio measures, rather than by the
            # lag-1 autocorrelation. Matching lag-1 alone leaves the variance on
            # the wrong timescale - the defect a discriminator found first.
            target = meas["window_var_ratio"]
            if meas["var"] > 0 and meas["var_smooth"] > 0:
                # The white part sits entirely inside the window, so it must be
                # removed before asking what the smooth part has to contribute.
                need = (target * meas["var"] - meas["var_white"]) / meas["var_smooth"]
                meas["phi"] = N.window_ratio_phi(float(np.clip(need, 1e-6, 1.0)),
                                                 meas.get("window", 30))
            else:
                meas["phi"] = 0.0
            rs.noise_params[key][s] = meas
            _resid_store.setdefault(key, {})[s] = resid - sub["unit"].map(per_unit).to_numpy()

    # Cross-channel residual correlation per group, for correlated generation.
    for key, per_sensor in _resid_store.items():
        cs = [c for c in informative if c in per_sensor]
        if len(cs) < 2:
            continue
        M = np.column_stack([per_sensor[c] for c in cs])
        with np.errstate(invalid="ignore", divide="ignore"):
            Cm = np.nan_to_num(np.corrcoef(M, rowvar=False), nan=0.0)
        rs.resid_corr[key] = {"cols": cs, "corr": Cm.tolist()}

    return rs


OUT_DIR = os.path.join(
    os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))),
    "data", "cmapss", "processed",
)


def main() -> None:
    import argparse
    ap = argparse.ArgumentParser(description="Fit the C-MAPSS response surface (A8).")
    ap.add_argument("--subset", default="FD001")
    ap.add_argument("--degree", type=int, default=2)
    ap.add_argument("--out-dir", default=OUT_DIR)
    args = ap.parse_args()

    cal_path = os.path.join(args.out_dir, f"calibration_{args.subset}.json")
    with open(cal_path) as fh:
        cal = json.load(fh)
    gains = {int(k): v for k, v in cal["calibrated_parameter"]["value_by_mode"].items()}
    unit_mode = {int(k): v for k, v in cal["unit_mode"].items()}

    rs = fit(args.subset, gains, degree=args.degree,
             unit_mode=unit_mode, mode_diag=cal["fault_modes"])
    path = os.path.join(args.out_dir, f"surrogate_{args.subset}.json")
    rs.save(path)

    train = P.load_split(args.subset, "train")
    health = assign_health(train, gains, unit_mode)
    regimes = assign_regimes(train, rs.regime_centres)
    row_mode = train["unit"].map(unit_mode).to_numpy()
    print(f"{args.subset}  degree={args.degree}  modes={rs.n_modes} "
          f"regimes={rs.regime_centres.shape[0]}  groups={len(rs.coef)}  "
          f"informative={len(rs.sensors)}  constant={len(rs.constant_sensors)}")
    print(f"  mode weights: {[round(w, 3) for w in rs.mode_weights]}")
    print(f"{'sensor':10s} {'R2':>7} {'between_sd':>11} {'within_sd':>10} {'total_sd':>9}")
    for s in rs.sensors:
        v = train[s].to_numpy(float)
        pred = np.empty_like(v)
        for mo in range(rs.n_modes):
            for r in range(rs.regime_centres.shape[0]):
                m = (regimes == r) & (row_mode == mo)
                if m.any():
                    pred[m] = np.polyval(rs.coef[gkey(mo, r)][s], health[m])
        r2 = 1 - ((v - pred) ** 2).sum() / ((v - v.mean()) ** 2).sum()
        b = np.mean([d[s] for d in rs.between_unit_sd.values() if s in d])
        w = np.mean([d[s] for d in rs.within_unit_sd.values() if s in d])
        print(f"{s:10s} {r2:7.3f} {b:11.4f} {w:10.4f} {v.std():9.4f}")
    print(f"-> {path}")


if __name__ == "__main__":
    main()
