#!/usr/bin/env python3
"""Export one engine's physics_v4 constants and reference runs for Simulink.

Writes, into the Simulink project folder (default ~/Documents/MATLAB/v4):

    rotax<N>_v4_params.m      every constant the Simulink model uses, printed
                              at full double precision (%.17g) - including the
                              ones physics_v4 derives at construction (critical-
                              altitude pressure ratio, knock reference, air-mass
                              calibration) and every value that needs exp/pow,
                              so MATLAB uses the identical doubles instead of
                              recomputing them through a different maths library.
    reference/<N>/<case>.csv      per-step inputs and UNROUNDED outputs of
                                  PistonEngineV4.step(), for verify_rotax_v4.m.
    reference/<N>/<case>_x0.csv   the initial state the run starts from.

The engine's hardware flags (turbocharged, intercooled, fuel_injected) are written too:
build_rotax_v4.m uses them to build the induction and fuel path that engine has.

Re-run after any change to physics_v4 so the Simulink model stays identical.

RUN
    backend/export_rotax_v4_simulink.py --engine 912 [--out ~/Documents/MATLAB/v4]
"""
from __future__ import annotations

import argparse
import csv
import math
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import physics_v4 as V

MODEL = "Rotax_914_ULF"          # set by --engine
H_FIELDS = list(V.Health().as_dict())
U_FIELDS = ["altitude_m", "airspeed_ms", "aoa_deg", "throttle", "isa_dev_c",
            "qnh_offset_pa", "humidity_frac", "fuel_octane_mon", "fuel_ethanol_frac",
            "cooling_airflow_factor", "electrical_load_a", "oil_thermostat_open",
            "target_lambda", "boost_limit_pa"]
OUT_FIELDS = [
    "engine_rpm", "torque_nm", "power_kw", "indicated_power_kw", "friction_power_kw",
    "fmep_bar", "air_density", "ambient_temp_c", "ambient_pressure_pa",
    "manifold_pressure_kpa", "boost_pressure_ratio", "charge_temp_c",
    "air_mass_flow_kgs", "volumetric_efficiency", "wastegate_position",
    "fuel_flow", "fuel_flow_kgs", "lambda", "combustion_efficiency",
    "thermal_efficiency", "knock_retard", "injection_timing",
    "prop_rpm", "prop_torque", "advance_ratio", "thrust",
    "egt", "cht", "coolant_temp", "oil_temp", "oil_pressure",
    "battery_voltage", "alternator_current", "alternator_capacity",
    "lift", "drag", "thrust_margin", "lift_weight_margin",
    "vibx", "viby", "vibz", "life_used_hours"]
MARGIN_FIELDS = ["m_cht", "m_egt", "m_oil_temp", "m_oil_press", "health_index"]


def g(x: float) -> str:
    return repr(float(x))          # shortest round-trip repr: exact double


def write_params(path: str) -> None:
    e = V.PistonEngineV4(MODEL, dt=0.01)
    s = e.spec
    d = e.prop_diameter
    two_pi = 2 * math.pi
    L = []
    add = lambda k, v, c="": L.append(f"eng.{k:<22s} = {g(v)};" + (f"   % {c}" if c else ""))
    L += [f"% {MODEL.replace('_', ' ')} - physics_v4 constants for the Simulink twin.",
          "% GENERATED by backend/export_rotax_v4_simulink.py from physics_v4.py.",
          "% Do not edit by hand: re-run the exporter after any physics change.",
          "% Every value is the exact double Python uses (shortest round-trip form).",
          "", "eng = struct();",
          f"eng.id = '{MODEL.split('_')[1]}';",
          f"eng.name = '{MODEL.replace('_', ' ')}';",
          f"eng.turbocharged = {int(s.turbocharged)};   % induction: turbocharger + wastegate",
          f"eng.intercooled = {int(s.intercooled)};    % charge-air cooler after the compressor",
          f"eng.fuel_injected = {int(s.fuel_injected)};  % EFI holds lambda; a carburettor drifts with density",
          "", "% -- solver: two shaft modes of physics_v4.step() --"]
    add("dt_dyn", 0.01, "dynamic model: explicit shaft integration (dt < 0.25)")
    add("dt_ds", 1.0, "dataset model: quasi-steady shaft (dt >= 0.25)")
    add("dth_dyn", 0.01 / 3600.0, "dt in hours, life accounting")
    add("dth_ds", 1.0 / 3600.0)
    add("alpha_ds", 1.0 - math.exp(-1.0 / V.PistonEngineV4.SHAFT_TAU), "1-exp(-dt/SHAFT_TAU), dataset relaxation")
    add("inertia", e.inertia, "kg.m^2 at the crank, ASSUMED")
    add("omega_min", s.idle_rpm * 2 * math.pi / 60.0 * 0.5, "rad/s, shaft clamp")
    add("omega_max", s.max_rpm * 1.15 * 2 * math.pi / 60.0, "rad/s, shaft clamp")
    add("bisect_tol", 0.5, "rad/s, bisection stop")
    L += ["", "% -- physical constants --"]
    add("two_pi", two_pi)
    add("R_AIR", V.R_AIR); add("R_VAP", 461.495); add("GAMMA", V.GAMMA)
    add("T0_ISA", V.T0_ISA); add("P0_ISA", V.P0_ISA); add("LAPSE", V.LAPSE); add("G0", V.G0)
    add("atm_exp", V.G0 / (V.LAPSE * V.R_AIR), "barometric exponent g0/(L*R)")
    add("LHV_AVGAS", V.LHV_AVGAS); add("LHV_ETHANOL", V.LHV_ETHANOL)
    add("AFR_STOICH", V.AFR_STOICH); add("AFR_STOICH_ETHANOL", V.AFR_STOICH_ETHANOL)
    add("comp_exp", (V.GAMMA - 1) / V.GAMMA, "(gamma-1)/gamma")
    add("otto_exp", -(V.GAMMA - 1), "-(gamma-1)")
    L += ["", "% -- calibrated / assumed model constants --"]
    for k in ("CYCLE_QUALITY", "DESIGN_OCTANE_MON", "VE_PEAK", "VE_PEAK_N", "VE_CURV_LO",
              "VE_CURV_HI", "EXHAUST_BACKPRESSURE", "UA_COOL", "UA_HEAD", "UA_OIL",
              "OIL_TSTAT_OPEN_C", "OIL_TSTAT_FULL_C", "CARB_DENSITY_EXP"):
        add(k, getattr(V, k))
    add("tstat_span", V.OIL_TSTAT_FULL_C - V.OIL_TSTAT_OPEN_C)
    add("bypass", 25.0 / 70.0, "oil cooler bypass fraction")
    add("one_minus_bypass", 1.0 - 25.0 / 70.0)
    L += ["", f"% -- {MODEL.replace('_', ' ')} geometry and ratings (published) --"]
    add("bore", s.bore_m); add("stroke", s.stroke_m); add("cylinders", s.cylinders)
    add("disp", s.displacement_m3, "m^3, pi/4*bore^2*stroke*cyl")
    add("two_stroke", 2.0 * s.stroke_m)
    add("CR", s.compression_ratio); add("CR_m1", s.compression_ratio - 1.0)
    add("rated_power", s.rated_power_w); add("rated_rpm", s.rated_rpm)
    add("idle_rpm", s.idle_rpm); add("max_rpm", s.max_rpm); add("gear", s.gear_ratio)
    add("max_map", s.max_map_pa, "Pa, manifold pressure limit")
    add("crit_alt", s.crit_alt_m, "m, critical altitude (0 = no turbo)")
    add("idle_map_frac", s.idle_map_frac); add("one_minus_idle", 1.0 - s.idle_map_frac)
    add("tbo", s.tbo_hours)
    add("m_cht", s.cht_mass_j_per_k); add("m_oil", s.oil_mass_j_per_k); add("m_cool", s.coolant_mass_j_per_k)
    add("size", s.rated_power_w / 84_500.0, "cooling scales with rated power")
    add("ua_head", V.UA_HEAD * (s.rated_power_w / 84_500.0))
    L += ["", "% -- derived at construction by physics_v4 (exact values) --"]
    add("ic_eff", 0.65, "intercooler effectiveness, new (physics_v4 ASSUMED)")
    add("pr_max", e.pr_max, "compressor ceiling: holds max_map up to crit_alt")
    add("pr_max_m1", e.pr_max - 1.0)
    add("knock_design", max(e.knock_design, 1e-6), "knock reference, hardest certified point")
    add("ve_scale", e.ve_scale, "air-mass calibration to rated power")
    L += ["", "% -- propeller and airframe --"]
    add("prop_d", d); add("prop_d4", d ** 4); add("prop_d5", d ** 5)
    add("wing_area", s.wing_area_m2); add("cd0", s.cd0); add("cd_k", s.cd_k)
    add("weight", s.mass_kg * V.G0, "N")
    L += ["", "% -- operability limits (Rotax operating manual) --"]
    add("cht_limit", s.cht_limit_c); add("cht_nom", s.cht_nominal_c)
    add("egt_limit", s.egt_limit_c); add("egt_nom", s.egt_nominal_c)
    add("oilt_limit", s.oil_temp_limit_c); add("oilt_nom", s.oil_temp_nominal_c)
    add("oilp_min", s.oil_press_min_bar); add("oilp_nom", s.oil_press_nominal_bar)
    add("oilp_min_low", s.oil_press_min_low_bar); add("oilp_nom_low", s.oil_press_nominal_low_bar)
    add("oilp_split_rpm", s.oil_press_split_rpm)
    add("cht_den", max(s.cht_limit_c - s.cht_nominal_c, 1e-6))
    add("egt_den", max(s.egt_limit_c - s.egt_nominal_c, 1e-6))
    add("oilt_den", max(s.oil_temp_limit_c - s.oil_temp_nominal_c, 1e-6))
    add("oilp_den", max(s.oil_press_nominal_bar - s.oil_press_min_bar, 1e-6))
    add("oilp_den_low", max(s.oil_press_nominal_low_bar - s.oil_press_min_low_bar, 1e-6))
    L += ["", "% -- vibration --"]
    add("sqrt2", math.sqrt(2.0)); add("cos07", math.cos(0.7))
    L += ["", "% -- default initial state: physics_v4 constructor (cold, at idle) --"]
    add("x0_omega", e.omega); add("x0_coolant", e.coolant_k); add("x0_cht", e.cht_k)
    add("x0_oil", e.oil_k); add("x0_egt", e.egt_k); add("x0_battery", e.battery_v)
    add("x0_life", e.life_used_h)
    L += ["", "% Bus field order used by the model (u = inputs, h = health modifiers)",
          "eng.u_fields = {" + ", ".join(f"'{f}'" for f in U_FIELDS) + "};",
          "eng.h_fields = {" + ", ".join(f"'{f}'" for f in H_FIELDS) + "};", ""]
    with open(path, "w") as fh:
        fh.write("\n".join(L))
    print(f"wrote {path}  ({sum(l.startswith('eng.') for l in L)} constants)")


# ---------------------------------------------------------------------------
def profile(n: int, dt: float) -> list:
    """A deliberately hard input profile that walks through every branch:
    idle, spool-up, full throttle, turbo ceiling above critical altitude, carb
    richening, knock (poor fuel, hot day), stall AoA, near-zero airspeed (the
    advance-ratio floor), thermostat stuck and working, electrical overload."""
    rows = []
    for k in range(n):
        f = k / max(n - 1, 1)
        t = k * dt
        rows.append({
            "altitude_m": 6800.0 * max(0.0, min(1.0, (f - 0.35) / 0.35)) if f < 0.9 else 300.0,
            "airspeed_ms": 0.0 if f < 0.05 else 30.0 + 28.0 * math.sin(f * 7.0) ** 2,
            "aoa_deg": 3.0 + 12.0 * max(0.0, math.sin(f * 11.0)),
            "throttle": (0.0 if f < 0.08 else 1.0 if f < 0.3 else
                         0.55 + 0.4 * math.sin(f * 9.0) if f < 0.85 else 0.2),
            "isa_dev_c": -10.0 + 38.0 * f,
            "qnh_offset_pa": 600.0 * math.sin(f * 3.0),
            "humidity_frac": 0.2 + 0.7 * f,
            "fuel_octane_mon": 91.0 if 0.5 < f < 0.7 else 95.0,
            "fuel_ethanol_frac": 0.10 if f > 0.6 else 0.0,
            "cooling_airflow_factor": 0.8 + 0.3 * f,
            "electrical_load_a": 12.0 + 30.0 * max(0.0, math.sin(f * 5.0)),
            "oil_thermostat_open": 0.0 if 0.4 < f < 0.55 else 1.0,
            "target_lambda": 0.86 + 0.14 * f,
            "boost_limit_pa": 0.0,
        })
    return rows


HEALTH_CASES = {
    "healthy": V.Health(),
    "degraded": V.Health(air_filter_mod=0.85, volumetric_eff_mod=0.95, compression_mod=0.92,
                         valve_leak_mod=0.9, turbo_eff_mod=0.8, turbo_flow_mod=0.85,
                         wastegate_mod=0.9, intercooler_mod=0.7, injector_flow_mod=0.93,
                         ignition_mod=0.95, combustion_eff_mod=0.96, friction_mod=1.15,
                         oil_pump_mod=0.88, oil_quality_mod=0.8, cooling_mod=0.85,
                         prop_eff_mod=0.94),
}


def write_reference(folder: str, name: str, dt: float, n: int, health: V.Health,
                    warm: bool) -> None:
    V.round = lambda x, nd=None: x          # step() reports rounded values; record the raw ones
    e = V.PistonEngineV4(MODEL, dt=dt)
    prof = profile(n, dt)
    u0 = inputs(prof[0])
    if warm:
        e.warm_start(u0, health)
    x0 = {"omega": e.omega, "coolant": e.coolant_k, "cht": e.cht_k, "oil": e.oil_k,
          "egt": e.egt_k, "battery": e.battery_v, "life": e.life_used_h}
    with open(os.path.join(folder, f"{name}_x0.csv"), "w", newline="") as fh:
        w = csv.writer(fh); w.writerow(list(x0)); w.writerow([g(v) for v in x0.values()])
    with open(os.path.join(folder, f"{name}_health.csv"), "w", newline="") as fh:
        w = csv.writer(fh); w.writerow(H_FIELDS); w.writerow([g(v) for v in health.as_dict().values()])
    with open(os.path.join(folder, f"{name}.csv"), "w", newline="") as fh:
        w = csv.writer(fh)
        w.writerow(["t"] + U_FIELDS + OUT_FIELDS + MARGIN_FIELDS)
        for k, row in enumerate(prof):
            o = e.step(inputs(row), health)
            m = e.margins(o)
            w.writerow([g(k * dt)] + [g(row[f]) for f in U_FIELDS]
                       + [g(o[f]) for f in OUT_FIELDS]
                       + [g(m["cht"]), g(m["egt"]), g(m["oil_temp"]), g(m["oil_press"]),
                          g(m["health_index"])])
    del V.round
    print(f"wrote reference/{os.path.basename(folder)}/{name}.csv  ({n} steps of {dt} s, {'warm' if warm else 'cold'} start)")


def inputs(row: dict) -> V.Inputs:
    kw = {k: row[k] for k in U_FIELDS}
    kw["oil_thermostat_open"] = bool(kw["oil_thermostat_open"])
    kw["boost_limit_pa"] = kw["boost_limit_pa"] or None
    return V.Inputs(**kw)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--engine", default="914", choices=["912", "914", "915", "916"])
    ap.add_argument("--out", default=os.path.expanduser("~/Documents/MATLAB/v4"))
    a = ap.parse_args()
    global MODEL
    MODEL = next(k for k in V.ENGINE_SPECS_V4 if k.split("_")[1] == a.engine)
    ref = os.path.join(a.out, "reference", a.engine)
    os.makedirs(ref, exist_ok=True)
    write_params(os.path.join(a.out, f"rotax{a.engine}_v4_params.m"))
    write_reference(ref, "dyn_healthy_cold", 0.01, 12000, HEALTH_CASES["healthy"], warm=False)
    write_reference(ref, "dyn_degraded_warm", 0.01, 12000, HEALTH_CASES["degraded"], warm=True)
    write_reference(ref, "ds_healthy_warm", 1.0, 900, HEALTH_CASES["healthy"], warm=True)
    write_reference(ref, "ds_degraded_warm", 1.0, 900, HEALTH_CASES["degraded"], warm=True)


if __name__ == "__main__":
    main()
