"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import Link from "next/link";
import { ArrowLeft, Film, RefreshCw, Sparkles, AlertTriangle, CheckCircle2 } from "lucide-react";
import { supabase } from "@/lib/supabase";
import Navbar from "@/components/Navbar";
import { simSecondsToRealHours, simRulHoursToPercent } from "@/lib/timeScale";
import { formatRulSimHours, isRulExtrapolated } from "@/lib/units";

const API = "http://localhost:8000";

type GroqResult = {
  status?: string;
  reason?: string;
  model?: string;
  risk?: string;
  headline?: string;
  summary?: string;
  findings?: string[];
  recommendations?: string[];
  recovered?: boolean;
  generated_at?: string;
};

type SimRow = {
  id: number;
  user_id: string;
  engine_model: string;
  started_at: string;
  ended_at: string | null;
  outcome: string | null;
  final_health_percent: number | null;
  final_rul_hours: number | null;
  final_telemetry: Record<string, unknown> | null;
  groq_result: GroqResult | null;
};

const RISK_STYLE: Record<string, string> = {
  low: "text-[#7fc87f] border-[#2f4a30] bg-[#0d150e]",
  moderate: "text-[#ffd27a] border-[#84642c] bg-[#1c1710]",
  high: "text-[#ff9a72] border-[#84432c] bg-[#21130f]",
};

export default function MissionReportPage() {
  const params = useParams();
  const id = Array.isArray(params?.id) ? params.id[0] : params?.id;
  const router = useRouter();

  const [loading, setLoading] = useState(true);
  const [notFound, setNotFound] = useState(false);
  const [sim, setSim] = useState<SimRow | null>(null);
  const [regenerating, setRegenerating] = useState(false);
  const [regenError, setRegenError] = useState<string | null>(null);
  const pollRef = useRef<ReturnType<typeof setInterval> | null>(null);

  const fetchSim = useCallback(async () => {
    const { data, error } = await supabase
      .from("simulations")
      .select("id, user_id, engine_model, started_at, ended_at, outcome, final_health_percent, final_rul_hours, final_telemetry, groq_result")
      .eq("id", id)
      .single();
    if (error || !data) return null;
    return data as SimRow;
  }, [id]);

  useEffect(() => {
    let cancelled = false;
    (async () => {
      const { data: { session } } = await supabase.auth.getSession();
      if (!session) { router.push("/login"); return; }
      const row = await fetchSim();
      if (cancelled) return;
      if (!row) { setNotFound(true); setLoading(false); return; }
      setSim(row);
      setLoading(false);
    })();
    return () => { cancelled = true; };
  }, [fetchSim, router]);

  // The summary is generated by a fire-and-forget task on /stop, so a run opened
  // immediately after landing may not have one yet. Poll until it lands, then stop.
  useEffect(() => {
    if (!sim || sim.groq_result) {
      if (pollRef.current) { clearInterval(pollRef.current); pollRef.current = null; }
      return;
    }
    let ticks = 0;
    pollRef.current = setInterval(async () => {
      ticks += 1;
      const row = await fetchSim();
      if (row?.groq_result) { setSim(row); }
      if (ticks >= 20 && pollRef.current) { clearInterval(pollRef.current); pollRef.current = null; }
    }, 3000);
    return () => { if (pollRef.current) clearInterval(pollRef.current); };
  }, [sim, fetchSim]);

  const regenerate = async () => {
    if (!sim) return;
    setRegenerating(true); setRegenError(null);
    try {
      const res = await fetch(`${API}/summarize/${sim.id}`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ user_id: sim.user_id }),
      });
      const json = await res.json();
      if (json.status !== "ok") throw new Error(json.detail || "summary unavailable");
      const row = await fetchSim();
      if (row) setSim(row);
    } catch (e) {
      setRegenError(e instanceof Error ? e.message : "Could not regenerate");
    } finally {
      setRegenerating(false);
    }
  };

  const g = sim?.groq_result ?? null;
  const wear = typeof sim?.final_telemetry?.wear === "number" ? (sim.final_telemetry.wear as number) : null;
  const simSeconds = typeof sim?.final_telemetry?.time === "number" ? (sim.final_telemetry.time as number) : null;

  return (
    <>
      <Navbar />
      <main className="pt-16 relative min-h-screen">
        <div className="absolute inset-0 grid-bg pointer-events-none opacity-50 z-0" />
        <div className="relative z-10 max-w-5xl mx-auto px-4 md:px-6 py-12">

          <Link href="/mission" className="inline-flex items-center gap-2 text-on-surface-variant hover:text-primary transition-colors text-[12px] mb-6">
            <ArrowLeft className="h-4 w-4" /> Back to missions
          </Link>

          {loading && <div className="text-on-surface-variant text-[13px]">Loading report&hellip;</div>}
          {notFound && <div className="text-on-surface-variant text-[13px]">Mission not found.</div>}

          {!loading && !notFound && sim && (
            <>
              <header className="flex flex-wrap items-start justify-between gap-4 mb-8">
                <div>
                  <h1 className="font-headline-display text-[26px] md:text-[32px] font-bold text-primary uppercase tracking-tight">
                    Mission Report
                    <span className="ml-3 text-[12px] font-mono text-tertiary/70 align-middle">ID #{sim.id}</span>
                  </h1>
                  <div className="text-[12px] text-on-surface-variant mt-1">
                    {sim.engine_model.replace(/_/g, " ")} &middot; {new Date(sim.started_at).toLocaleString()}
                    {sim.outcome && <> &middot; {sim.outcome.toUpperCase()}</>}
                  </div>
                </div>
                <Link
                  href={`/mission/replay/${sim.id}`}
                  className="rounded bg-surface/80 border border-outline-variant/30 px-5 py-2.5 text-[11px] font-bold uppercase tracking-[0.1em] text-on-surface-variant hover:text-primary transition-all flex items-center gap-2"
                >
                  <Film className="h-4 w-4" /> Replay
                </Link>
              </header>

              {/* headline stats */}
              <div className="grid grid-cols-2 lg:grid-cols-4 gap-4 mb-8">
                <div className="bg-surface/80 border border-outline-variant/30 rounded-lg p-5">
                  <div className="text-[11px] uppercase tracking-[0.1em] text-on-surface-variant">Final Health</div>
                  <div className="text-3xl font-bold text-primary">
                    {sim.final_health_percent === null ? "--" : `${sim.final_health_percent.toFixed(0)}%`}
                  </div>
                </div>
                <div className="bg-surface/80 border border-outline-variant/30 rounded-lg p-5">
                  <div className="text-[11px] uppercase tracking-[0.1em] text-on-surface-variant">Final RUL</div>
                  {/* Same self-normalising percentage ai.py computes and the cockpit
                      shows - one scale everywhere. Raw hours are given on the model's
                      OWN scale underneath; they are not converted to real-world hours,
                      because that mapping breaks above ai.py's 5.556 sim h ceiling. */}
                  <div className="text-3xl font-bold text-primary">
                    {sim.final_rul_hours === null ? "--" : `${Math.min(100, simRulHoursToPercent(sim.final_rul_hours, simSeconds ?? undefined)).toFixed(0)}%`}
                  </div>
                  {sim.final_rul_hours !== null && (
                    <div className="text-[10px] uppercase tracking-[0.1em] text-on-surface-variant mt-1">
                      {formatRulSimHours(sim.final_rul_hours)}
                      {isRulExtrapolated(sim.final_rul_hours) && (
                        <span className="text-tertiary"> &middot; extrapolated</span>
                      )}
                    </div>
                  )}
                </div>
                <div className="bg-surface/80 border border-outline-variant/30 rounded-lg p-5">
                  <div className="text-[11px] uppercase tracking-[0.1em] text-on-surface-variant">Mission Time</div>
                  <div className="text-3xl font-bold text-primary">
                    {simSeconds === null ? "--" : `${simSeconds.toFixed(0)}s`}
                  </div>
                  {simSeconds !== null && (
                    <div className="text-[10px] uppercase tracking-[0.1em] text-on-surface-variant mt-1">
                      {simSecondsToRealHours(simSeconds).toFixed(2)} h real
                    </div>
                  )}
                </div>
                <div className="bg-surface/80 border border-outline-variant/30 rounded-lg p-5">
                  <div className="text-[11px] uppercase tracking-[0.1em] text-on-surface-variant">Accumulated Wear</div>
                  <div className="text-3xl font-bold text-primary">{wear === null ? "--" : wear.toFixed(4)}</div>
                </div>
              </div>

              {/* AI narrative */}
              <section className="mb-8">
                <div className="flex items-center justify-between mb-4">
                  <h2 className="text-sm font-bold text-primary uppercase tracking-[0.1em] flex items-center gap-2">
                    <Sparkles className="h-4 w-4 text-tertiary" /> Post-Flight Analysis
                  </h2>
                  <button
                    onClick={regenerate}
                    disabled={regenerating}
                    className="rounded bg-surface/80 border border-outline-variant/30 px-4 py-2 text-[10px] font-bold uppercase tracking-[0.1em] text-on-surface-variant hover:text-primary transition-all disabled:opacity-40 flex items-center gap-2"
                  >
                    <RefreshCw className={`h-3.5 w-3.5 ${regenerating ? "animate-spin" : ""}`} />
                    {regenerating ? "Generating" : "Regenerate"}
                  </button>
                </div>

                {regenError && (
                  <div className="mb-3 text-[12px] text-[#ff9a72]">{regenError}</div>
                )}

                {!g && (
                  <div className="bg-surface/80 border border-outline-variant/30 rounded-lg p-5 flex items-center gap-3">
                    <RefreshCw className="h-4 w-4 text-tertiary animate-spin" />
                    <p className="text-[13px] text-on-surface-variant">
                      Generating post-flight analysis&hellip; This runs in the background after a
                      mission ends, so it may take a few seconds to appear.
                    </p>
                  </div>
                )}

                {g && g.status !== "ok" && (
                  <div className="bg-surface/80 border border-outline-variant/30 rounded-lg p-5 flex items-start gap-3">
                    <AlertTriangle className="h-4 w-4 text-tertiary shrink-0 mt-0.5" />
                    <div>
                      <p className="text-[13px] text-primary mb-1">Analysis unavailable</p>
                      <p className="text-[12px] text-on-surface-variant">{g.reason ?? "Unknown reason."}</p>
                    </div>
                  </div>
                )}

                {g && g.status === "ok" && (
                  <div className="bg-surface/80 border border-outline-variant/30 rounded-lg p-5">
                    <div className="flex flex-wrap items-start justify-between gap-3 mb-3">
                      {/* Plain text only - this is third-party model output rendered
                          next to first-party telemetry; never dangerouslySetInnerHTML. */}
                      <h3 className="text-primary font-bold text-[15px] leading-snug flex-1 min-w-0">
                        {g.headline}
                      </h3>
                      {g.risk && (
                        <span className={`shrink-0 rounded border px-2.5 py-1 text-[10px] font-bold uppercase tracking-[0.1em] ${RISK_STYLE[g.risk] ?? RISK_STYLE.low}`}>
                          {g.risk} risk
                        </span>
                      )}
                    </div>

                    <p className="text-[13px] leading-relaxed text-on-surface-variant whitespace-pre-line mb-5">
                      {g.summary}
                    </p>

                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                      <div className="bg-surface/60 border border-outline-variant/30 rounded p-4">
                        <div className="text-[10px] uppercase tracking-[0.1em] text-tertiary/80 mb-2">Findings</div>
                        <ul className="space-y-2">
                          {(g.findings ?? []).map((f, i) => (
                            <li key={i} className="flex gap-2 text-[12px] text-on-surface-variant leading-relaxed">
                              <AlertTriangle className="h-3.5 w-3.5 text-tertiary shrink-0 mt-0.5" />
                              <span>{f}</span>
                            </li>
                          ))}
                          {(g.findings ?? []).length === 0 && (
                            <li className="text-[12px] text-on-surface-variant">None recorded.</li>
                          )}
                        </ul>
                      </div>
                      <div className="bg-surface/60 border border-outline-variant/30 rounded p-4">
                        <div className="text-[10px] uppercase tracking-[0.1em] text-tertiary/80 mb-2">Recommendations</div>
                        <ul className="space-y-2">
                          {(g.recommendations ?? []).map((r, i) => (
                            <li key={i} className="flex gap-2 text-[12px] text-on-surface-variant leading-relaxed">
                              <CheckCircle2 className="h-3.5 w-3.5 text-[#7fc87f] shrink-0 mt-0.5" />
                              <span>{r}</span>
                            </li>
                          ))}
                          {(g.recommendations ?? []).length === 0 && (
                            <li className="text-[12px] text-on-surface-variant">None recorded.</li>
                          )}
                        </ul>
                      </div>
                    </div>

                    <div className="mt-4 pt-3 border-t border-outline-variant/20 text-[10px] uppercase tracking-[0.1em] text-on-surface-variant">
                      Generated by {g.model}
                      {g.generated_at && <> &middot; {new Date(g.generated_at).toLocaleString()}</>}
                      {g.recovered && <> &middot; recovered from malformed response</>}
                    </div>
                  </div>
                )}
              </section>
            </>
          )}
        </div>
      </main>
    </>
  );
}
